### ISSUE TITLE
Update Package.swift to Swift 5.3

### ISSUE THREAD

**Issue by shaps80** [cx-org/CombineX#102]
Would be great to get this updated if possible. My main reason for advocating for this is to avoid consumers (myself included) from having test dependencies included, since this was resolved in the most recent update.

**Comment by ddddxxx** [comment]
We already have [Swift 5.2 manifest](https://github.com/cx-org/CombineX/blob/master/Package%40swift-5.2.swift) in the master branch which should have resolved this issue.

**Comment by shaps80** [comment]
Yep seems to have with recent release. Thanks!
