### ISSUE TITLE
Zip3 Operator

### ISSUE THREAD

**Issue by shahzadmajeed** [cx-org/CombineX#105]
Hi,

I am trying to test Zip3 operator and it doesn't seem to be working as expected:

**My Code:**

`var disposable: [AnyCancellable] = []
func testZip3() {
      
        let p1 = [3, 4, 5].cx.publisher
        let p2 = ["Hello", "World"].cx.publisher
        let p3 = [0.2, 0.6].cx.publisher

        Publishers.Zip3(p1, p2, p3)
        .print()
        .sink(receiveCompletion: { result in
            print(result)
        }, receiveValue: { (r1, r2, r3) in
            print(r1, r2, r3)
        })
        .store(in: &disposable)
    }`

**Output:**
`: receive subscription: (MapError)
: request unlimited
: receive finished
finished
`

PS: Same code works fine when I use Apple Combine.

**Comment by ddddxxx** [comment]
It seems `Zip` eagerly consumed all value from p1 and got `.finished` prematurely.

**Comment by ddddxxx** [comment]
please try #106

**Comment by shahzadmajeed** [comment]
Thank you!
