### ISSUE TITLE
Set Environment Variable CX_COMBINE_IMPLEMENTATION = "CombineX" for CI

### ISSUE THREAD

**Issue by shahzadmajeed** [cx-org/CombineX#107]
Hi,

Environment variables seem tricky and Xcode doesn't seem to recognize them (I'm trying Environment Variables setting under executable target scheme). I am wondering why didn't you choose launch arguments instead (under executable target scheme) ?

PS: It works if I set environment variable before launching Xcode though.

Thanks for helping!

Shahzad

**Comment by ddddxxx** [comment]
I'm not quite sure what you are talking about. Did you mean this?
<img width="721" alt="image" src="https://user-images.githubusercontent.com/11691433/109753462-45b02680-7c1d-11eb-9949-ac476f199ef8.png">

The Environment variable is applied to the compiler, not your application. `CX_COMBINE_IMPLEMENTATION` must present when resolving [Package.swift](https://github.com/cx-org/CombineX/blob/master/Package%40swift-5.2.swift#L124). It's too late to do anything inside Xcode as package resolution already completed.

**Comment by ddddxxx** [comment]
As you found out, you need to launch Xcode with environment variable. Here is a guide https://github.com/cx-org/CombineX/wiki/Combine-Compatible-Package#usage

**Comment by shahzadmajeed** [comment]
I see, I wrong about application then. I thought Xcode loads environment variables on launch but that's not true. These are only for compilers to make this stuff available to the app you building and it is already late because packages are resolved as you said. For now, I am using .command script included in your example project
