### ISSUE TITLE
Outdated CocoaPods version

### ISSUE THREAD

**Issue by BucekJiri** [cx-org/CombineX#112]
The latest version released to [CocoaPods](https://cocoapods.org/pods/CombineX) is 0.1.1. 

Running `pod install --repo-update` installs this version, not the latest 0.3.0.

**Comment by ddddxxx** [comment]
I've released version 0.3.1 with correct pod configuration. But I'm not able to publish updates to cocoapods.org. Please use this repo instead for now.

```
pod 'CombineX', :git => 'https://github.com/cx-org/CombineX.git', :tag => '0.3.1'
```

**Comment by luoxiu** [comment]
Sorry for the late reply, I keep meeting lint failures. I will spend more time on this tomorrow.

**Comment by luoxiu** [comment]
Fixed.

https://github.com/CocoaPods/Specs/commit/a9bf85d82319c9d5a0f8010c72f697941a764d34
