### ISSUE TITLE
Build failure when use CXShim + Combine + iOS (No such module 'Combine')

### ISSUE THREAD

**Issue by ddddxxx** [cx-org/CombineX#117]
When use CXShim with system Combine and target on 'Any iOS Device', we got "No such module 'Combine'" error. As reported in #116 and sbertix/Swiftagram#191.

This is because `CXShim` always have low system requirement. To re-export system Combine, we need to bump platform to iOS 13.0.

However, system requirement is applied to both `CombineX` and `CXShim`. We can make it configurable via environment variable, but we can't make them both work out of the box. Currently `CX_CONTINUOUS_INTEGRATION=YES CX_COMBINE_IMPLEMENTATION=Combine` will force high platform and `CX_COMBINE_IMPLEMENTATION=CombineX` will force low platform.

I believe `CombineX` and `CXShim` are equally important. Mandatory env configuration can make integration significantly more obscure. The best solution I can think of is to move `CXShim` to a separate repo. So we can lift system requirement just for `CXShim`. This would be a breaking change.

**Comment by ddddxxx** [comment]
ping @luoxiu

**Comment by luoxiu** [comment]
Moving CXShim to a separate repo is ok to me, it does deserve its own repo.
