### ISSUE TITLE
When trying to use debounce neither RunLoop nor DispatchQueue seems to conform to Scheduler

### ISSUE THREAD

**Issue by jakobmygind** [cx-org/CombineX#12]
![image](https://user-images.githubusercontent.com/8362263/66309468-fec7df80-e909-11e9-8954-4bf043805798.png)

If I import Combine instead this code builds
I would like to fix it, but I am not sure how 😅

**Comment by luoxiu** [comment]
Hi, @jakobmygind , you should use `DispatchQueue.main.cx` in this scenario.

For some unavoidable reasons, the apis of Combine and CombineX are a little different. Check out [CXFoundation](https://github.com/cx-org/CXFoundation) and [CXCompitable](https://github.com/cx-org/CXCompatible) for more information!

And, thanks for the feedback, I am very happy to know that someone is paying attention to this library. 😉

**Comment by jakobmygind** [comment]
@luoxiu Ah, thank you!
