### ISSUE TITLE
Rename `CXWrappers` -> `CX`

### ISSUE THREAD

**Issue by ddddxxx** [cx-org/CombineX#123]
`CXWrappers` is a misleading namespace, and it leaks implementation detail. When use with system Combine, `CXWrappers.DispatchQueue` is simply a typealias to `DispatchQueue` and doesn't wrap anything.

I think `CX` is a better namespace, also `CX.DispatchQueue` is symmetrical with `DispatchQueue.CX`.

**Comment by ddddxxx** [comment]
ping @luoxiu

**Comment by luoxiu** [comment]
If look at it this way, `CX` does make more sense.

**Comment by ddddxxx** [comment]
How about `CXWrapper`, `CXWrapping`, and `CXSelfWrapping`? They're not meant to be used yet still public. Give then underscore prefix? Keep them as is?

**Comment by ddddxxx** [comment]
I get name collision when use in NSObject subclass (global `CX` and `NSObject.CX`). It seems we need to also remove `SomeClass.CX` and only use `CX.SomeClass`. Is this worth it?
