### ISSUE TITLE
Why requires macOS 10.12?

### ISSUE THREAD

**Issue by ddddxxx** [cx-org/CombineX#2]
I've changed supported platform to `.macOS(.v10_10)` and everything works just fine.

**Comment by luoxiu** [comment]
@ddddxxx , you are right, CombineX doesn't relay on platforms(the only platform-related thing it uses is Lock), so  I think it will work fine on both iOS 8 and macOS 10.10.

Will fix this during lunch break.

**Comment by luoxiu** [comment]
Or you can create pr if you want! BTW, I'm an enthusiastic [LyricsX](https://github.com/ddddxxx/LyricsX) user, greate work! 👍👍👍
