### ISSUE TITLE
Debounce keeps emitting values even though debounced publisher is not publishing

### ISSUE THREAD

**Issue by jakobmygind** [cx-org/CombineX#46]
Debounce seems to get into an endless loop emitting last received value.
This code:

```Swift
 let pub = PassthroughSubject<Int, Never>()
        
        pub
            .debounce(for: 1.0, scheduler: DispatchQueue.main.cx)
            .sink(receiveValue: {
                print("received: \($0) at: \(Date())")
            })
            .store(in: &subscribers)
        
        (0...10).forEach(pub.send)
```

Gives this result:

```
received: 10 at: 2019-11-07 10:16:58 +0000
received: 10 at: 2019-11-07 10:16:59 +0000
received: 10 at: 2019-11-07 10:17:00 +0000
received: 10 at: 2019-11-07 10:17:01 +0000
received: 10 at: 2019-11-07 10:17:02 +0000
received: 10 at: 2019-11-07 10:17:03 +0000
received: 10 at: 2019-11-07 10:17:04 +0000
received: 10 at: 2019-11-07 10:17:05 +0000
received: 10 at: 2019-11-07 10:17:06 +0000
received: 10 at: 2019-11-07 10:17:07 +0000
received: 10 at: 2019-11-07 10:17:08 +0000
received: 10 at: 2019-11-07 10:17:09 +0000
received: 10 at: 2019-11-07 10:17:10 +0000
received: 10 at: 2019-11-07 10:17:11 +0000
received: 10 at: 2019-11-07 10:17:12 +0000
received: 10 at: 2019-11-07 10:17:13 +0000
received: 10 at: 2019-11-07 10:17:14 +0000
```

**Comment by ddddxxx** [comment]
I find [a test case](https://github.com/cx-org/CombineX/blob/master/Tests/CombineXTests/Publishers/DebounceSpec.swift#L50-L64) described this behaviour. It seems to be intended, but I can't reproduce this behaviour with Combine. @luoxiu

**Comment by ddddxxx** [comment]
Actually the CI [is completely broken](https://travis-ci.org/cx-org/CombineX/jobs/608612717#L8857)...

**Comment by luoxiu** [comment]
According to [this test](https://github.com/cx-org/CombineX/blob/master/Tests/CombineXTests/Publishers/DebounceSpec.swift#L50-L64) combine has the same behavior.
@jakobmygind Have you tried combine?

**Comment by jakobmygind** [comment]
@luoxiu Yes, I am switching back and forth and Native Combine does not do that. That use case where debounce keeps publishing without input seems like a very specific one.

Afaik Debounce does not emit any values if new input was received in the debounce interval and finally publishes 1 event when no new inputs were received and the time expired.

**Comment by luoxiu** [comment]
@jakobmygind I will investigate this, thanks for the feedback! You are making cx better!

**Comment by jakobmygind** [comment]
@luoxiu Thank you!
