### ISSUE TITLE
consider adapting Apple's implementations of Foundation and Dispatch publishers

### ISSUE THREAD

**Issue by mayoff** [cx-org/CombineX#75]
Apple's implementations of the Foundation and Dispatch publishers and schedulers are part of the Swift open-source project. Have you considered adapting those implementations for CX?

Here are the files of interest:

- [`Publishers+KeyValueObserving.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Publishers%2BKeyValueObserving.swift)
- [`Publishers+Locking.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Publishers%2BLocking.swift)
- [`Publishers+NotificationCenter.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Publishers%2BNotificationCenter.swift)
- [`Publishers+Timer.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Publishers%2BTimer.swift)
- [`Publishers+URLSession.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Publishers%2BURLSession.swift)
- [`Schedulers+Date.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Schedulers%2BDate.swift)
- [`Schedulers+OperationQueue.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Schedulers%2BOperationQueue.swift)
- [`Schedulers+RunLoop.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Schedulers%2BRunLoop.swift)
- [`Schedulers+DispatchQueue.swift`](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Dispatch/Schedulers%2BDispatchQueue.swift)

**Comment by ddddxxx** [comment]
Great! It seems like Swift open-source project is a few versions ahead of the system built-in. [This](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/Publishers%2BKeyValueObserving.swift#L84) doesn’t exist in macOS 10.15.4. I’ll adopt the rest.
